// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zarcqftkumvryibndmhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphcmNxZnRrdW12cnlpYm5kbWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzYwMTAsImV4cCI6MjA2NzgxMjAxMH0.hGzMlEr0-SQ-_w8QPKhN4MxBnSHMjzmEuusGX_zqQeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});